---
# tasks file for vmwaretools/Debian

- name: Installing Open VMware Tools (open-vm-tools)
  apt:
    name: "{{ vmtools_pkg }}"
    update_cache: yes
  register: result
  until: result is succeeded
  notify:
    - start vmtoolsd
    - enabled vmtoolsd
